### ISSUE TITLE
SimpleLDAP is not a constructor

### ISSUE THREAD

**Issue by harirehm** [jxjj/simple-ldap-search#10]
I just copy pasted your code for a simple LDAP connection. I got the following error.

> var ldap = new SimpleLDAP(config);
>            ^
> 
> TypeError: SimpleLDAP is not a constructor
>     at Object.<anonymous> (C:\Users\561634\workspace_node1\mailsender\app.js:155:12)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)
>     at Function.Module.runMain (module.js:676:10)
>     at startup (bootstrap_node.js:187:16)
>     at bootstrap_node.js:608:3
>

**Comment by jxjj** [comment]
Is it imported into your project? Something like:

```js
import SimpleLDAP from 'simple-ldap-search';
```

Could you link a simplified project that replicates the issue?

**Comment by gh0st** [comment]
@harirehm is probably trying to execute this in node. Not in a browser.

**Comment by shukriadams** [comment]
You're probably using require instead of import, try adding .default to your require call

    let SimpleLDAP = require('simple-ldap-search').default;
