### ISSUE TITLE
integer converting in clean breaks telephone numbers.

### ISSUE THREAD

**Issue by digitalstaub** [jxjj/simple-ldap-search#12]
e.g. if your number is 00491234567, you'll get 491234567.
It's hard to get the amount of leading zeros back.

**Comment by jxjj** [comment]
Ah, yes. I can see why that would be a problem. I'll look into it.

**Comment by jxjj** [comment]
We'll avoid converting integer strings that have leading zeros (unless it's "0").

So: 
```js
cleanEntry({ thingy: "00491234567"}) // remains the string "00491234567"
cleanEntry({ thingy: "1234567" }) // converts to number 1234567
cleanEntry({ thingy: "0" })  // converts to number 0
```
