### ISSUE TITLE
Not working import

### ISSUE THREAD

**Issue by sergeeximius** [jxjj/simple-ldap-search#15]
I copied the code from the manual. Got an error:

![image](https://user-images.githubusercontent.com/33500911/62757876-b5841c80-ba8d-11e9-8de6-f5f1fed141f3.png)

**Comment by jxjj** [comment]
To use `import` in the current version of node, you'll need to use something like [babeljs](https://babeljs.io/) or [esm](https://github.com/standard-things/esm).

With plain node, try using

```js
const SimpleLDAP = require("simple-ldap-search").default;
```
