### ISSUE TITLE
Add support for ldaps/tls search

### ISSUE THREAD

**Issue by rawroland** [jxjj/simple-ldap-search#16]
Hello,
There is currently no support for ldaps search. Would you be open to accepting a pull request which implements this?

**Comment by nicoschuck** [comment]
I would like that too!

**Comment by itdxsd** [comment]
Yes please. Active Directory over SSL also.

**Comment by schmetzyannick** [comment]
Support is build in by the underlining package ldapjs, when you need to provide tls options have a look at my pull request

**Comment by jxjj** [comment]
This should be resolved by #31 .

Thanks @schmetzyannick for the PR.
